apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: 28thmayworkflow
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
metadata:
  stages/v1alpha1:
    - name: env1
      jobs:
        - deploy-to-env1
    - name: env2
      jobs:
        - deploy-to-env2
    - name: env3
      jobs:
        - deploy-to-env3
jobs:
  deploy-to-env1:
    steps:
      - name: Deploy to env1
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Deploying to env1"
  deploy-to-env2:
    needs:
      - deploy-to-env1
    steps:
      - name: Deploy to env2
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Deploying to env2"
  deploy-to-env3:
    needs:
      - deploy-to-env2
    steps:
      - name: Deploy to env3
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Deploying to env3"
